#!/bin/bash

CSV="coils.csv"

echo "Select a wire by entering it's corresponding number"
echo ""

# List wire types from CSV
while read p; do
    IFS=, arr=($p)
    echo "${arr[0]}) ${arr[1]} (${arr[2]})"
done <coils.csv

echo "Enter wire number?"
read -r WIRE

# Get the selected wire 
IFS=, wire=($(sed -n ${WIRE}p coils.csv))

echo ""
echo "You have selected: ${wire[1]} (${wire[2]}) @ ${wire[3]} Ohms per inch"

echo ""
echo "What is the diameter of your coil in mm"
read -r DIAMETER