#!/bin/bash

# deal with variable inputs

for i in "$@"
do
case $i in
	# Get value for volts (V)
	-v=*|--volts=*)
	V="${i#*=}"
	shift
	;;

	# Get value for ohms (R)
	-r=*|--ohms=*)
	R="${i#*=}"
	shift
	;;

	# Get value for watts (P)
	-p=*|--watts=*)
	P="${i#*=}"
	shift
	;;

	# GET value for amps (I)
	-i=*|--amps=*)
	I="${i#*=}"
	shift
	;;

	# unrecognised
	*)
	;;
esac
done

# Check if any variables have been entered
if [ -z "$V" ] && [ -z "$R" ] && [ -z "$P" ] && [ -z "$I" ];
then
	echo "No values have been passed to the script."
	echo ""
	echo "You will be requested to enter the values you know, if you do not know a specific value then just press [Return] without entering a value.
	You must enter exactly 2 values."
	echo ""
	echo ""
	
	echo "Enter a value for Volts (V):"
	
	read -r V
	
	echo "Enter a value for Ohms (R):"
	
	read -r R
	
	echo "Enter a value for Watts (P):"
	
	read -r P
	
	echo "Enter a value for Amps (I):"
	
	read -r I
	
fi

# Check if values are numeric 
# This function will exit if the input does not follow the rules
# null
# numeric 
# numeric . numeric
validateNumber ()
{
	if [ -n "$1" ]
	then
		if ! [[ "$1" =~ ^[0-9]+$ ]] && ! [[ "$1" =~ ^[-+]?[0-9]+\.?[0-9]*$ ]] ; 
		then
			echo "Error: '$1' is not a number"
			exit
		fi
	fi
}

# Check the input data 
validateNumber $V
validateNumber $R
validateNumber $P
validateNumber $I

# Do the calculations
if [ -n "$V" ] && [ -n "$R" ] ;
then 
	echo "Calculating from Volts (V) and Ohms (R)" ;
	P=$(bc -l <<< "scale=2;($V*$V/$R)") ;
	I=$(bc -l <<< "scale=2;($V/$R)") ;

elif [ -n "$V" ] && [ -n "$P" ] ;
then
	echo "Calculating from Volts (V) and Watts (P)" ;
	R=$(bc -l <<< "scale=2;($V*$V/$P)") ;
	I=$(bc -l <<< "scale=2;($P/$V)") ;
	
elif [ -n "$V" ] && [ -n "$I" ] ;
then
	echo "Calculating from Volts (V) and Amps (I)" ;
	R=$(bc -l <<< "scale=2;($V/$I)") ;
	P=$(bc -l <<< "scale=2;($V*$I)") ;

elif [ -n "$R" ] && [ -n "$P" ] ;
then
	echo "Calculating from Ohms (R) and Watts (P)" ;
	V=$(bc -l <<< "scale=2;sqrt($P*$R)") ;
	I=$(bc -l <<< "scale=2;sqrt($P/$R)") ;
	
elif [ -n "$R" ] && [ -n "$I" ] ;
then
	echo "Calculating from Ohms (R) and Amps (I)" ;
	V=$(bc -l <<< "scale=2;($I*$R)") ;
	P=$(bc -l <<< "scale=2;($I*$I*$R)") ;
	
elif [ -n "$P" ] && [ -n "$I" ] ;
then
	echo "Calculating from Watts (P) and Amps (I)" ;
	V=$(bc -l <<< "scale=2;($P/$I)") ;
	R=$(bc -l <<< "scale=2;($P/($I*$I))") ;
	
else 
	echo "There is not enough data to work out the missing values, at least 2 values are required!"
	exit
fi

# For testing only
echo "Volts (V)  = ${V}"
echo "Ohms (R)   = ${R}"
echo "Watts (P)  = ${P}"
echo "Amps (I)   = ${I}"

echo ""